// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtzl5XQK-3IpxYw4TYpkFMiDugiZb0sT8',
    appId: '1:906321675056:web:3e54ce0abc1ded6bb7bef5',
    messagingSenderId: '906321675056',
    projectId: 'panther-app-mvp',
    authDomain: 'panther-app-mvp.firebaseapp.com',
    storageBucket: 'panther-app-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARtlt4OOmsxpfW6b7YXvK5BiGHIG0blo8',
    appId: '1:906321675056:android:4ed529f60ef48b01b7bef5',
    messagingSenderId: '906321675056',
    projectId: 'panther-app-mvp',
    storageBucket: 'panther-app-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB77jlI7ggmVjCrIfV8efVgvU7d3zPqvI',
    appId: '1:906321675056:ios:763151d04b477e99b7bef5',
    messagingSenderId: '906321675056',
    projectId: 'panther-app-mvp',
    storageBucket: 'panther-app-mvp.firebasestorage.app',
    iosBundleId: 'com.panther.pantherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB77jlI7ggmVjCrIfV8efVgvU7d3zPqvI',
    appId: '1:906321675056:ios:763151d04b477e99b7bef5',
    messagingSenderId: '906321675056',
    projectId: 'panther-app-mvp',
    storageBucket: 'panther-app-mvp.firebasestorage.app',
    iosBundleId: 'com.panther.pantherApp',
  );
}
